

# POST http://localhost:3000/users/sign-in
# Content-Type: application/json

# {
#   "email": "thanh.mathe@upos.vn",
#   "password": ""
# }


POST http://localhost:3000/blogs/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwODY1NzQ0MSwiZXhwIjoxNzA4ODMwMjQxfQ.m88WQGMkBSmYePJ0zVr_JAi3KXIayg0pElj0sycoRRE

{
  "title": "Title vista blog 1 ",
  "banner": "https://example.com/image-url",
  "des": "this is short desc",
  "content": {
    "blocks": [1,2]
  },
  "tags": ["tag1", "tag2"]
}