

# POST http://localhost:3000/users/sign-in
# Content-Type: application/json

# {
#   "email": "thanh.mathe@upos.vn",
#   "password": ""
# }


# POST http://localhost:3000/blogs/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTI3Njc3NywiZXhwIjoxNzA5NDQ5NTc3fQ.Gm5TziRQQkQ4oo1wfC01k5UoShGn1utcBh_fNqWFQuY

# {
#   "title": "Title vista blog 1 ",
#   "banner": "https://example.com/image-url",
#   "des": "this is short desc",
#   "content": {
#     "blocks": [1,2]
#   },
#   "tags": ["tag1", "tag2"]
# }


# GET http://localhost:3000/blogs/trending
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTUzNzA1NiwiZXhwIjoxNzA5NzA5ODU2fQ.-gI4vQT5NmtJcb5CBHh2V-WgaMNaCxousURSq-f6h9Q


POST http://localhost:3000/blogs/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTUzNzA1NiwiZXhwIjoxNzA5NzA5ODU2fQ.-gI4vQT5NmtJcb5CBHh2V-WgaMNaCxousURSq-f6h9Q

{
  "tag": "food"
}