

# POST http://localhost:3000/users/sign-in
# Content-Type: application/json

# {
#   "email": "thanhmtfpt@gmail.com",
#   "password": "Nana0901"
# }



# POST http://localhost:3000/blogs/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTI3Njc3NywiZXhwIjoxNzA5NDQ5NTc3fQ.Gm5TziRQQkQ4oo1wfC01k5UoShGn1utcBh_fNqWFQuY

# {
#   "title": "Title vista blog 1 ",
#   "banner": "https://example.com/image-url",
#   "des": "this is short desc",
#   "content": {
#     "blocks": [1,2]
#   },
#   "tags": ["tag1", "tag2"]
# }


# GET http://localhost:3000/blogs/trending
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTUzNzA1NiwiZXhwIjoxNzA5NzA5ODU2fQ.-gI4vQT5NmtJcb5CBHh2V-WgaMNaCxousURSq-f6h9Q


# POST http://localhost:3000/users/profile
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTc5ODg3NiwiZXhwIjoxNzA5OTcxNjc2fQ.aO8v59FcPeZYnej0HqRFcfwAUDIlNA5BOXcQsIYvctM

# {
#   "username": "thanh.mathe"
# }



# POST http://localhost:3000/blogs/detail
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcwOTg4NTk3MCwiZXhwIjoxNzEwMDU4NzcwfQ.ChJN1tN-f7uyIVmyWO58gtA5wJ4xhccStH605U-lk78

# {
#   "blog_id": "Tr-i-nghi-m-v-n-h-a-c-o-t-i-H-i-AnlRQdhPDEZ0Tde8P-ZnIE8"
# }

POST http://localhost:3000/blogs/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Y2VjYzAyMmExMTYzOTEwZTA4OTJhYSIsImlhdCI6MTcxMDE1MDgwOCwiZXhwIjoxNzEwMzIzNjA4fQ.Ris7P5UHgfQPPLVtsn2cmcERFD0AwOdUhNwyAc9tuto

{
  "blog_id": "Tr-i-nghi-m-v-n-h-a-c-o-t-i-H-i-AnlRQdhPDEZ0Tde8P-ZnIE8"
}